// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
    seed: 'tsx prisma/seed/index.ts',
  },
  datasource: {
    url: 'postgresql://android_backend_user:EVRcjY9VBLFPz3sFh9jTsshMHbCURmWC@dpg-d5q29u75r7bs738a9pd0-a:5432/android_backend',
  },
});
